PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>

SELECT ?sub ?p ?o
WHERE {
       # Retrieve all facts from public companies / entities with LEIs / entitites with ISINs
       {
       ?sub p:P31 ?statement0 . # Entities which are instances of businesses or its subclasses
       ?statement0 (ps:P31/(wdt:P279*)) wd:Q4830453 .
       }
       ?sub ?p ?o.
}
LIMIT 10
