SELECT DISTINCT ?concept ?conceptLabel WHERE {
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en,de,it,fr". }
  {
    SELECT DISTINCT ?concept WHERE {
      {
        ?concept p:P31 ?statement0.
        ?statement0 (ps:P31) wd:Q106905561.
      }
      UNION
      {
        ?concept p:P31 ?statement1.
        ?statement1 (ps:P31) wd:Q21451178.
      }
      UNION
      {
        ?concept p:P31 ?statement2.
        ?statement2 (ps:P31) wd:Q64588497.
      }
      UNION
      {
        ?concept p:P31 ?statement3.
        ?statement3 (ps:P31) wd:Q832161.
      }
      UNION
      {
        ?concept p:P31 ?statement4.
        ?statement4 (ps:P31) wd:Q1167393.
      }
      UNION
      {
        ?concept p:P31 ?statement5.
        ?statement5 (ps:P31) wd:Q29028649.
      }
    }
  }
}
