PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>
PREFIX p: <http://www.wikidata.org/prop/>
PREFIX ps: <http://www.wikidata.org/prop/statement/>

SELECT ?sub ?o
WHERE {
       # Retrieve all statements with a given property
       {
       ?sub {{property}} ?o . # Facts associated with LEI
       }
}
