name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  docker:
    runs-on: ubuntu-latest
    container: ghcr.io/trr266/esef-jl:main
    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v3
      - 
        name: test Package
        run: |
          julia --project=. -e "using Pkg; Pkg.test()"
